name: Sync ReactFlux Content to Main

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:38 and 12:38 UTC every day
    - cron: '38 */12 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout YOUR repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main
        repository: ivancarlosti/minifluxreader
        clean: true
        persist-credentials: true

    - name: Reset Git remote
      run: |
        git remote remove origin || true
        git remote add origin https://github.com/ivancarlosti/minifluxreader.git
        git remote -v

    - name: Download ReactFlux content
      run: |
        # Create temp folder OUTSIDE repository
        mkdir -p /tmp/reactflux_temp
        cd /tmp/reactflux_temp
        git clone --branch gh-pages --depth 1 https://github.com/electh/ReactFlux.git
        echo "=== Copying files ==="
        rsync -av \
          --exclude='.github' \
          --exclude='.git' \
          --exclude='favicon.ico' \
          ReactFlux/ "$GITHUB_WORKSPACE/"
        echo "=== Files copied to repository ==="
        ls -la "$GITHUB_WORKSPACE"

    - name: Cleanup temp files
      run: |
        echo "=== Cleaning up ==="
        rm -rf /tmp/reactflux_temp
        echo "Temp folder contents:"
        ls -la /tmp/reactflux_temp 2>/dev/null || echo "Temp folder removed"

    - name: Commit changes (skip if only manifest.json changed)
      run: |
        cd "$GITHUB_WORKSPACE"
        git config --global user.email "ivan@ivancarlos.com.br"
        git config --global user.name "ivancarlosti"

        git add .
        changes=$(git status --porcelain)
        # Extract changed filenames only
        changed_files=$(echo "$changes" | awk '{print $2}' | grep .)

        if [ -z "$changes" ]; then
          echo "No changes to commit"
          exit 0
        elif [ "$(echo "$changed_files" | wc -l)" -eq 1 ] && [ "$changed_files" = "manifest.json" ]; then
          echo "Only manifest.json changed, skipping commit"
          exit 0
        else
          git commit -m "Sync ReactFlux content [▶️]"
          echo "=== Commit details ==="
          git show --stat
        fi

    - name: Push changes
      if: success()
      run: |
        cd "$GITHUB_WORKSPACE"
        git push \
          https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/ivancarlosti/minifluxreader.git \
          HEAD:main
        echo "=== Push successful ==="
